# docker-composeのバージョン、最新は3
version: '3'

services:
  jupyterlab:
      container_name: cname
      build:
        context: .
        dockerfile: Dockerfile
      # image: jupyter/datascience-notebook   # 特定のimageを使う場合（build か　imageのどちらかを使う）
      # コンテナの/jobyan/work以下をホストの./workにおいてデータ永続化する。
      volumes:
         - "../../:/home/jovyan/work"
      # (ホストポート:コンテナポート)
      ports:
        - 9999:8888
      # パスワード設定などとりあえずめんどくさいのでtokenを空にしてすぐ使えるようにする。
      # (起動テスト用なので実際にはパスワードなどを設定してください)
      tty: true
      stdin_open: true
      command: jupyter lab --allow-root --ip=0.0.0.0 --no-browser